/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "messages": {
        "errors": {
            "not_found": string;
            "internal_server": string;
        };
        "common": {
            "created": string;
            "updated": string;
            "retrieved": string;
            "deleted": string;
            "blocked": string;
            "unblocked": string;
        };
    };
    "terms": {
        "user": string;
    };
    "validations": {
        "string": string;
        "date": string;
        "not_empty": string;
        "max": string;
        "min": string;
        "already_exists": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
