version: '3.3'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:user-db
    command: sleep infinity

  user-db:
    image: postgres:16.2-alpine
    container_name: user-db
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - userdb-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=U3B^2ykXk3WSt#YsdvDuM!
      - POSTGRES_USER=admin
      - POSTGRES_DB=user-app

  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    environment:
      - ADMINER_DESIGN=galkaev
      - ADMINER_DEFAULT_SERVER=user-db
    ports:
      - 8001:8080
  
  user-redis:
    container_name: user-redis
    image: 'redis:alpine'
    ports:
      - '8004:6379'

volumes:
  userdb-data: